# Exercise part of MITx - Machine Learning with Python (Lecture 17 - Reinforcement Learning 1)
------

## Recall
----

An agent is trying to navigate a one-dimensional grid consisting of 5 cells. At each step, the agent has only one action to choose from, i.e. it moves to the cell on the immediate right.

<b>Note:</b> The reward function is defined to be <b>R(s,a,s′) = R(s)</b>, <b>R(s=5) = 1</b> and <b>R(s)=0</b> otherwise. Note that we get the reward when we are leaving from the current state. When it reaches the rightmost cell, it stays for one more time step and then receives a reward of +1 and comes to a halt.

Let <b>V_(i)</b> denote the value function of state i, the ith cell starting from left.

Let <b>V_k(i)</b> denote the value function estimate at state i at the kth step of the value iteration algorithm. Let V∗0(i) denote the initialization of this estimate.

Use the discount factor <b>γ=0.5</b>.

We will write the functions V_k as arrays below, i.e. as [V∗k(1)V∗k(2)V∗k(3)V∗k(4)V∗k(5)].


Initialize by setting V∗0(i)=0 for all i:<b>


     V_0	=	[0 0 0 0 0] 	 


</b>Then, using the value iteration update rule, we get:<b>

 	V_1	=	[0 0 0 0 1],	 	 
 	V_2	=	[0 0 0 0.5 1]	 	 

</b><b>Note:</b> Note that as soon as the agent takes the first action to reach cell 5, it stays for one more step and halts and does not take any more action, so we set V∗k+1(5)=V∗k(5) for all k≥1.

## Exercise 
-----
<b>(Changes to be made on the exercise proposed in the Lecture)</b>

Consider the same one-dimensional grid with reward values as in the first few problems in this vertical. However, consider the following change to the transition probabilities: At any given grid location the agent can choose to either stay at the location or move to an adjacent grid location. If the agent chooses to stay at the location, such an action is successful with probability 1/2 and:

- if the agent is at the leftmost or rightmost grid location it ends up at its neighboring grid location with probability 1/2,

- if the agent is at any of the inner grid locations it has a probability 1/4 each of ending up at either of the neighboring locations.

If the agent chooses to move (either left or right) at any of the inner grid locations, such an action is successful with probability 1/3 and with probability 2/3 it fails to move, and:

- if the agent chooses to move left at the leftmost grid location, then the action ends up exactly the same as choosing to stay, i.e., staying at the leftmost grid location with probability 1/2, and ends up at its neighboring grid location with probability 1/2,

- if the agent chooses to move right at the rightmost grid location, then the action ends up exactly the same as choosing to stay, i.e., staying at the rightmost grid location with probability 1/2, and ends up at its neighboring grid location with probability 1/2.

Let <b>γ=0.5</b>.

Run the value iteration algorithm for 100 iterations. Use any computational software of your choice.

In [2]:
import numpy as np

In [3]:
K = 100
gamma = 1/2
V = np.zeros(5)

R = np.array([[[0, 0, 0, 0, 0],
           [0, 0, 0, 0, 0],
           [0, 0, 0, 0, 0]],

          [[0, 0, 0, 0, 0],
           [0, 0, 0, 0, 0],
           [0, 0, 0, 0, 0]],

          [[0, 0, 0, 0, 0],
           [0, 0, 0, 0, 0],
           [0, 0, 0, 0, 0]],

          [[0, 0, 0, 0, 0],
           [0, 0, 0, 0, 0],
           [0, 0, 0, 0, 0]],

          [[1, 1, 1, 1, 1],
           [1, 1, 1, 1, 1],
           [1, 1, 1, 1, 1]]])

# Matrix (5x3x5) for 5 states and 3 actions
# a1 = stay
# a2 = move right
# a3 = move left


T = np.array([[[1/2, 1/2, 0, 0, 0],
           [2/3, 1/3, 0, 0, 0],
           [1/2, 1/2, 0, 0, 0]],

          [[1/4, 1/2, 1/4, 0, 0],
           [0, 2/3, 1/3, 0, 0],
           [1/3, 2/3, 0, 0, 0]],

          [[0, 1/4, 1/2, 1/4, 0],
           [0, 0, 2/3, 1/3, 0],
           [0, 1/3, 2/3, 0, 0]],

          [[0, 0, 1/4, 1/2, 1/4],
           [0, 0, 0, 2/3, 1/3],
           [0, 0, 1/3, 2/3, 0]],

          [[0, 0, 0, 1/2, 1/2],
           [0, 0, 0, 1/2, 1/2],
           [0, 0, 0, 1/3, 2/3]]])

for k in range(0,K):
    Q = T * (R + gamma * V)
    V = np.max(Q.sum(axis=2), axis = 1)
    print(V)

[0. 0. 0. 0. 1.]
[0.         0.         0.         0.16666667 1.33333333]
[0.         0.         0.02777778 0.27777778 1.47222222]
[0.         0.00462963 0.05555556 0.33796296 1.53703704]
[1.15740741e-03 1.08024691e-02 7.48456790e-02 3.68827160e-01
 1.56867284e+00]
[0.00298997 0.0160751  0.08641975 0.38438786 1.58436214]
[0.00476627 0.01976166 0.09287123 0.39218964 1.59218536]
[0.00613198 0.02206576 0.09632202 0.39609411 1.59609339]
[0.00704943 0.02340892 0.09812302 0.39804693 1.59804682]
[0.00761459 0.02415681 0.09904883 0.39902345 1.59902343]
[0.00794285 0.02456041 0.09952018 0.39951172 1.59951172]
[0.00812581 0.0247735  0.09975868 0.39975586 1.59975586]
[0.00822483 0.02488428 0.09987887 0.39987793 1.59987793]
[0.00827728 0.02494124 0.09993928 0.39993896 1.59993896]
[0.00830463 0.02497029 0.09996959 0.39996948 1.59996948]
[0.00831873 0.02498503 0.09998478 0.39998474 1.59998474]
[0.00832594 0.02499247 0.09999238 0.39999237 1.59999237]
[0.0083296  0.02499622 0.09999619 0.39999619 1.599

## Exercise II
-----

In [ ]:
K = 2
gamma = 1
V = np.zeros(4)

T = np.array([[[0, 0, 0, 0],
               [0, 1, 0, 0]
              ],
              [[1, 0, 0, 0],
               [0, 0, 1, 0]
              ],
              [[0, 1, 0, 0],
               [0, 0, 0, 1]
              ],
              [[0, 0, 1, 0],
               [0, 0, 0, 0]
              ]])

R = np.array([[[ 0,  0,  0,  0],
               [10, 10, 10, 10]
              ],
              [[10, 10, 10, 10],
               [ 1,  1,  1,  1]
              ],
              [[ 1,  1,  1,  1],
               [ 1,  1,  1,  1]
              ],
              [[ 1,  1,  1,  1],
               [ 0,  0,  0,  0]
              ]])

for k in range(0,K):
    Q = T * (R + gamma * V)
    V = np.max(Q.sum(axis=2), axis = 1)
    print(V)